# Docker Compose version v2.29.7
services:
  geospatial-data-analysis:
    image: geospatial-data-analysis
    build: .
    volumes:
      - data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  data:
